#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 stharrold
# SPDX-License-Identifier: Apache-2.0
"""Audit CLAUDE.md files against the v8.9 discipline rubric.

Checks for:
  1. Tier-B stub pattern (frontmatter + auto-generated Contents list,
     no real content). The anti-pattern removed in v8.9.
  2. Oversized files (>500 lines) that should be split into
     docs/architecture.md or per-subsystem scoped files.
  3. Dated section headers that will rot (e.g. "## Foo (2026-04-02)").

Exit codes:
  0: clean (or warnings only in non-strict mode)
  1: strict-mode failure (stubs or oversized files present)

See .claude/skills/claude-md-hygiene/SKILL.md for rationale and usage.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Heuristics
OVERSIZED_LINES = 500
STUB_LINE_LIMIT = 80  # files larger than this cannot be stubs

# Section headers that indicate an autogenerated Tier-B stub
STUB_HEADER_PATTERNS = [
    re.compile(r"^## Contents\s*$", re.MULTILINE),
    re.compile(r"^## Related\s*$", re.MULTILINE),
    re.compile(r"^## Related Documentation\s*$", re.MULTILINE),
    re.compile(r"^\*\*Child Directories:\*\*", re.MULTILINE),
]

# Frontmatter marker used by the deleted generator
STUB_FRONTMATTER_RE = re.compile(r"^---\s*\ntype:\s*claude-context\s*\n", re.MULTILINE)

# Dated section headers to flag as drift risk: (YYYY-MM-DD), (2026-04-02),
# (updated ...), etc. Intentionally broad; matches within markdown headings.
DATED_HEADER_RE = re.compile(
    r"^#+ .*(?:\((?:19|20)\d\d[-/]?\d\d?[-/]?\d\d?.*?\)|\(updated\s+[^)]*\)).*$",
    re.MULTILINE,
)


@dataclass
class AuditResult:
    stubs: list[tuple[Path, int]] = field(default_factory=list)
    oversized: list[tuple[Path, int]] = field(default_factory=list)
    dated: list[tuple[Path, int, str]] = field(default_factory=list)
    clean: list[tuple[Path, int]] = field(default_factory=list)

    @property
    def total_scanned(self) -> int:
        return len(self.stubs) + len(self.oversized) + len(self.dated) + len(self.clean)

    @property
    def total_issues(self) -> int:
        # A single file can be both stub AND dated; count each issue once
        return len(self.stubs) + len(self.oversized) + len(self.dated)


def find_claude_md_files(root: Path) -> list[Path]:
    """Return all CLAUDE.md files under root, skipping the usual exclusions."""
    exclusions = {
        ".git",
        ".tmp",
        ".venv",
        "venv",
        "__pycache__",
        "node_modules",
        "ARCHIVED",
        "archived",
        "_site",
    }
    files = []
    for path in root.rglob("CLAUDE.md"):
        if any(part in exclusions for part in path.parts):
            continue
        files.append(path)
    return sorted(files)


def looks_like_stub(content: str, line_count: int) -> bool:
    """Return True if the file matches the Tier-B stub pattern.

    Heuristic: small file (< STUB_LINE_LIMIT lines) with claude-context
    frontmatter OR at least two of the stub header markers.
    """
    if line_count > STUB_LINE_LIMIT:
        return False

    if STUB_FRONTMATTER_RE.search(content):
        return True

    stub_markers = sum(1 for pattern in STUB_HEADER_PATTERNS if pattern.search(content))
    return stub_markers >= 2


def find_dated_headers(content: str) -> list[tuple[int, str]]:
    """Return (line_number, header_text) for each dated section header."""
    matches = []
    for line_num, line in enumerate(content.splitlines(), start=1):
        if DATED_HEADER_RE.match(line):
            matches.append((line_num, line.strip()))
    return matches


def audit_file(path: Path) -> tuple[str, int, list[tuple[int, str]]]:
    """Audit a single CLAUDE.md file.

    Returns (category, line_count, dated_headers) where category is one
    of: 'stub', 'oversized', 'clean'. A file can also have dated_headers
    regardless of category.
    """
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        print(f"  [ERROR] {path}: {e}", file=sys.stderr)
        return "clean", 0, []

    line_count = content.count("\n") + (0 if content.endswith("\n") else 1)
    dated = find_dated_headers(content)

    if looks_like_stub(content, line_count):
        return "stub", line_count, dated
    if line_count > OVERSIZED_LINES:
        return "oversized", line_count, dated
    return "clean", line_count, dated


def audit(root: Path) -> AuditResult:
    result = AuditResult()
    for path in find_claude_md_files(root):
        category, line_count, dated = audit_file(path)

        if category == "stub":
            result.stubs.append((path, line_count))
        elif category == "oversized":
            result.oversized.append((path, line_count))
        else:
            result.clean.append((path, line_count))

        for line_num, header in dated:
            result.dated.append((path, line_num, header))

    return result


def format_report(result: AuditResult, root: Path) -> str:
    """Human-readable report."""
    lines = ["=== claude-md-hygiene audit ===", ""]

    def rel(p: Path) -> str:
        try:
            return str(p.relative_to(root))
        except ValueError:
            return str(p)

    if result.stubs:
        lines.append(f"[STUBS] {len(result.stubs)} files match the Tier-B stub pattern:")
        for path, lc in result.stubs:
            lines.append(f"  {rel(path)} ({lc} lines)")
        lines.append("")

    if result.oversized:
        lines.append(f"[OVERSIZED] {len(result.oversized)} files exceed {OVERSIZED_LINES} lines:")
        for path, lc in sorted(result.oversized, key=lambda x: -x[1]):
            lines.append(f"  {rel(path)} ({lc} lines)")
        lines.append("")

    if result.dated:
        lines.append(f"[DATED] {len(result.dated)} dated section headers:")
        for path, line_num, header in result.dated:
            lines.append(f"  {rel(path)}:{line_num} {header}")
        lines.append("")

    if result.clean:
        lines.append(f"[CLEAN] {len(result.clean)} files pass all checks:")
        for path, lc in sorted(result.clean, key=lambda x: x[1]):
            lines.append(f"  {rel(path)} ({lc} lines)")
        lines.append("")

    lines.append(f"Total: {result.total_scanned} files scanned, {result.total_issues} issues.")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Directory to scan (default: current working directory)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 if any STUBS or OVERSIZED files are found (DATED is always a warning)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Print only the summary line, not the per-file breakdown",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    if not root.exists():
        print(f"Error: root directory {root} does not exist", file=sys.stderr)
        return 2

    result = audit(root)

    if args.quiet:
        print(f"claude-md-hygiene: {result.total_scanned} scanned, {len(result.stubs)} stub, {len(result.oversized)} oversized, {len(result.dated)} dated")
    else:
        print(format_report(result, root))

    if args.strict and (result.stubs or result.oversized):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
